#settings for SleepingServerStarter

serverName: YourServerName [Sleeping]
serverPort: 25565
loginMessage: ...Waking server up, come back in a minute...
serverOnlineMode: true

webPort: 0 	 					# 0 to disable web hosting, 8123default dynmap
webDir: plugins/dynmap/web 	# dir of dynmap web

startMinecraft: 1 				# 0 to disable	
minecraftCommand: java -Xms1G -Xmx1G -jar paper.jar nogui # 1G change to any free ram amount
version: 1.19.3